### ISSUE TITLE
可以请教一下MFC如何读取显示RAW图吗

### ISSUE THREAD

**Issue by Qishuqian** [Vaczzy/MFC-SimpleGobang#3]
可以请教一下MFC如何读取显示RAW图吗

**Comment by Vaczzy** [comment]
抱歉，这份代码是我大二时候写的。大三疫情在家整理到了github，现由于时间间隔久，主要研究方向变动，对于MFC的一些细节也记不清了，恕不能回答你的问题。你或许可以找到MFC与RAW图相关的API来解决这一问题
